/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrunkRouteImport } from './routes/trunk'
import { Route as TrendWatchRouteImport } from './routes/trend-watch'
import { Route as TreehouseStatusRouteImport } from './routes/treehouse-status'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as RootRoomRouteImport } from './routes/root-room'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LevelsRouteImport } from './routes/levels'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const TrunkRoute = TrunkRouteImport.update({
  id: '/trunk',
  path: '/trunk',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendWatchRoute = TrendWatchRouteImport.update({
  id: '/trend-watch',
  path: '/trend-watch',
  getParentRoute: () => rootRouteImport,
} as any)
const TreehouseStatusRoute = TreehouseStatusRouteImport.update({
  id: '/treehouse-status',
  path: '/treehouse-status',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const RootRoomRoute = RootRoomRouteImport.update({
  id: '/root-room',
  path: '/root-room',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelsRoute = LevelsRouteImport.update({
  id: '/levels',
  path: '/levels',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/levels': typeof LevelsRoute
  '/library': typeof LibraryRoute
  '/root-room': typeof RootRoomRoute
  '/signin': typeof SigninRoute
  '/treehouse-status': typeof TreehouseStatusRoute
  '/trend-watch': typeof TrendWatchRoute
  '/trunk': typeof TrunkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/levels': typeof LevelsRoute
  '/library': typeof LibraryRoute
  '/root-room': typeof RootRoomRoute
  '/signin': typeof SigninRoute
  '/treehouse-status': typeof TreehouseStatusRoute
  '/trend-watch': typeof TrendWatchRoute
  '/trunk': typeof TrunkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/levels': typeof LevelsRoute
  '/library': typeof LibraryRoute
  '/root-room': typeof RootRoomRoute
  '/signin': typeof SigninRoute
  '/treehouse-status': typeof TreehouseStatusRoute
  '/trend-watch': typeof TrendWatchRoute
  '/trunk': typeof TrunkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/levels'
    | '/library'
    | '/root-room'
    | '/signin'
    | '/treehouse-status'
    | '/trend-watch'
    | '/trunk'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/levels'
    | '/library'
    | '/root-room'
    | '/signin'
    | '/treehouse-status'
    | '/trend-watch'
    | '/trunk'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/levels'
    | '/library'
    | '/root-room'
    | '/signin'
    | '/treehouse-status'
    | '/trend-watch'
    | '/trunk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LevelsRoute: typeof LevelsRoute
  LibraryRoute: typeof LibraryRoute
  RootRoomRoute: typeof RootRoomRoute
  SigninRoute: typeof SigninRoute
  TreehouseStatusRoute: typeof TreehouseStatusRoute
  TrendWatchRoute: typeof TrendWatchRoute
  TrunkRoute: typeof TrunkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trunk': {
      id: '/trunk'
      path: '/trunk'
      fullPath: '/trunk'
      preLoaderRoute: typeof TrunkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trend-watch': {
      id: '/trend-watch'
      path: '/trend-watch'
      fullPath: '/trend-watch'
      preLoaderRoute: typeof TrendWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treehouse-status': {
      id: '/treehouse-status'
      path: '/treehouse-status'
      fullPath: '/treehouse-status'
      preLoaderRoute: typeof TreehouseStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/root-room': {
      id: '/root-room'
      path: '/root-room'
      fullPath: '/root-room'
      preLoaderRoute: typeof RootRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels': {
      id: '/levels'
      path: '/levels'
      fullPath: '/levels'
      preLoaderRoute: typeof LevelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LevelsRoute: LevelsRoute,
  LibraryRoute: LibraryRoute,
  RootRoomRoute: RootRoomRoute,
  SigninRoute: SigninRoute,
  TreehouseStatusRoute: TreehouseStatusRoute,
  TrendWatchRoute: TrendWatchRoute,
  TrunkRoute: TrunkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
