/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrunkRouteImport } from './routes/trunk'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as RootRoomRouteImport } from './routes/root-room'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const TrunkRoute = TrunkRouteImport.update({
  id: '/trunk',
  path: '/trunk',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const RootRoomRoute = RootRoomRouteImport.update({
  id: '/root-room',
  path: '/root-room',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/root-room': typeof RootRoomRoute
  '/signin': typeof SigninRoute
  '/trunk': typeof TrunkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/root-room': typeof RootRoomRoute
  '/signin': typeof SigninRoute
  '/trunk': typeof TrunkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/root-room': typeof RootRoomRoute
  '/signin': typeof SigninRoute
  '/trunk': typeof TrunkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/root-room' | '/signin' | '/trunk'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/root-room' | '/signin' | '/trunk'
  id: '__root__' | '/' | '/dashboard' | '/root-room' | '/signin' | '/trunk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  RootRoomRoute: typeof RootRoomRoute
  SigninRoute: typeof SigninRoute
  TrunkRoute: typeof TrunkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trunk': {
      id: '/trunk'
      path: '/trunk'
      fullPath: '/trunk'
      preLoaderRoute: typeof TrunkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/root-room': {
      id: '/root-room'
      path: '/root-room'
      fullPath: '/root-room'
      preLoaderRoute: typeof RootRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  RootRoomRoute: RootRoomRoute,
  SigninRoute: SigninRoute,
  TrunkRoute: TrunkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
